### ISSUE TITLE
Need to be able to edit

### ISSUE THREAD

**Issue by terazus** [ISAcommons/ISAcommons.github.io#5]
Hello,
Would you give me permission over this repo please? Susanna has asked for modifications that I unfortunatly can't do.

Tx :)

Dom

**Comment by djcomlab** [comment]
Hey Dom!

I am neither an owner or member of the repo, or even the ISAcommons org anymore.

This only happens if someone kicked me out. I don't know who or how it happened like this.

Good luck.

**Comment by proccaserra** [comment]
thank you @agbeltran
